### ISSUE TITLE
Time Synchronization Issues

### ISSUE THREAD

**Issue by bhairavmehta95** [ethz-asl/elevation_mapping#40]
I am using a bag file to publish the pose and point cloud topics, but this is the error I get from the elevation mapping topic. 

`[ERROR] [1492450225.324741178]: Requested update with time stamp 0.000000, but time of last update was 1492450225.073660.`

I have tried to set the parameter of `use_sim_time` to True, but if I do that, the elevation mapping node does not initialize. Is there any work around for this issue, or is there a way I can help out to add this feature if it does not already exist?

**Comment by Pyy666666** [comment]
hallo, I also encountered this problem. Have you sloved this problem?Thanks a lot .
