### ISSUE TITLE
ERROR: cannot launch node of type [elevation_mapping/elevation_mapping]: can't locate node [elevation_mapping] in package [elevation_mapping]

### ISSUE THREAD

**Issue by luiscarlosfeliz** [ethz-asl/elevation_mapping#58]
I'm using ROS kinetic and the compilation worked. What could be causing this?

**Comment by marco-tranzatto** [comment]
Hi,

can you please share the whole error you get in the console and not paste it as title?
Also, did you source your catkin workspace after you compiled the package and before you tried to launch the node?

**Comment by luiscarlosfeliz** [comment]
marco-tranzatto, I used catkin_make_isolated for this, wich created a devel_isolated dir. 
So to solve it the source has to be changed to:

source devel_isolated/setup.bash
