### ISSUE TITLE
How to get PoseWithCovarianceStamped from a tf???

### ISSUE THREAD

**Issue by rob3a** [ethz-asl/elevation_mapping#61]
I get the odometry in a tf so I have transform it to PoseWithCovarianceStamped, but the problem is that i do not have any covariance. Is there any problem giving Pose withou covariance?

**Comment by reinzor** [comment]
The idea of the fuse step in the map update method is that it takes the covariances of the measurements into account and fuses this to a coherent map. You could just manually add a covariance matrix based on some gaussian noise that describes the pose uncertainty of your robot.

**Comment by aybakana** [comment]
The script below listens tf and publishes posewithcovariancestamped -> 

[ground_truth_pose_publisher.py](https://github.com/ethz-asl/elevation_mapping/blob/master/elevation_mapping_demos/scripts/ground_truth_pose_publisher.py )

**Comment by TT22TY** [comment]
> The script below listens tf and publishes posewithcovariancestamped
> 
> [ground_truth_pose_publisher.py](https://github.com/ethz-asl/elevation_mapping/blob/master/elevation_mapping_demos/scripts/ground_truth_pose_publisher.py)

@aybakana ，hello, the script you provide does not exist, could you please share it again, thank you very much~

**Comment by maximilianwulf** [comment]
Hi @TT22TY, 

[tf_to_pose_publisher.py](https://github.com/ANYbotics/elevation_mapping/blob/master/elevation_mapping_demos/scripts/tf_to_pose_publisher.py) in the demo package should do the same.
