### ISSUE TITLE
How to save Elevation Map?

### ISSUE THREAD

**Issue by aybakana** [ethz-asl/elevation_mapping#67]
Is there a standard way to save and read an elevation map to a file and from a file?

**Comment by draliii** [comment]
Take a look at the [gridmap](https://github.com/ethz-asl/grid_map) package. The paper included shows how to work with GridMap. You can convert the GridMap message from elevation mapping to GridMap, then convert that to OpenCV Mat or other formats. GridMap's docs cover this nicely.
