### ISSUE TITLE
sensor parameters

### ISSUE THREAD

**Issue by ashnarayan13** [ethz-asl/elevation_mapping#78]
Hi, 

I want to test the elevation mapping on a velodyne lidar. 
Unfortunately, I couldn't understand what the parameters mean.

sensor_processor/min_radius: 0.018
sensor_processor/beam_angle: 0.0006
sensor_processor/beam_constant: 0.0015

Thank you

**Comment by pfankhauser** [comment]
From [here](elevation_mapping/elevation_mapping/src/sensor_processors/LaserSensorProcessor.cpp):

Anisotropic laser range sensor model:
> standardDeviationInBeamDirection = minRadius
> standardDeviationOfBeamRadius = beamConstant + beamAngle * measurementDistance

More infos here: 

> Taken from: Pomerleau, F.; Breitenmoser, A; Ming Liu; Colas, F.; Siegwart, R.,
> "Noise characterization of depth sensors for surface inspections,"
> International Conference on Applied Robotics for the Power Industry (CARPI), 2012.
